swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  user/profile/transactions:
    get:
      security:
      - Bearer: []
      tags:
        - All Transactions
      summary: User Transactions API
      description: API to distribute the list of transactions for the current month
      parameters:
      - type: string
        in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
      produces:
        - application/json
      responses:
        "200":
          description: The list of all transactions, successfully recovered
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  user/profile/transactions/{transactionid}:
    get:
      security:
      - Bearer: []
      tags:
       - User transaction
      summary: Search for a transaction using the id
      description: search for a transaction using the id
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transactionsId
          description: ID of transaction to fetch
          required: true
          type: string
      produces:
        - application/json
      responses:
        "201":
          description: The Search Transaction, successfully recovered
          schema:
            $ref: "#/definitions/TransactionItem"
        "400":
          description: Request id does not exist
        "500":
          description: Internal Server Error
    put:
      security:
      - Bearer: []
      tags:
      - Update an Transaction
      summary: Update an transaction
      description: Update an transaction
      parameters:
        - in: header
          name: Autorization
          description: Attach Bearer JWTtoken
          type: string
          required: true
        - in: path
          name: transactionsId
          description: ID of transaction to fetch
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionItem'
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/TransactionItem'
        '400':
          description: Invalid ID
        '404':
          description: Transaction not found
        '405':
          description: Validation exception
definitions:
  TransactionItem:
    properties:
      id:
        type: string
        description: transaction id
      title:
        type: string
        description: transaction title
      amount:
        type: integer
        description: transaction amount
      description:
        type: string
        description: transaction description